### ISSUE TITLE
resources

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/OpenACC-CUDA-beginners#1]
@zhmurov @jigo3635 did you look into these resources from Nvidia?
https://github.com/gpuhackathons-org/gpubootcamp/tree/master/hpc
Both under `openacc` and `nways`

**Comment by jigo3635** [comment]
I will use part of material. Thanks

**Comment by jigo3635** [comment]
@wikfeldt 

I have already used some materials from Nvidia.

There is license

"This material is released by NVIDIA Corporation under the Creative Commons Attribution 4.0 International (CC BY 4.0).". I just looked at this

https://creativecommons.org/licenses/by/4.0/

"Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so 
in any reasonable manner, but not in any way that suggests the licensor endorses you or your use."

So should we add also the **license** for us !?
